# Generated by Django 3.1.7 on 2021-04-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='braintree_id',
            new_name='transaction_reference_id',
        ),
    ]
